name: 'Kontakt-Person'
description: 'Verwende <em>Kontakt-Person</em>, um Profile von Personen zu erstellen und zu verwalten, die den Abteilungen der Organisation zugeordnet sind.'
third_party_settings:
  node_title_help_text:
    title_help: 'Haupttitel der Seite. Wird für Meta-Daten, Menüeintrag und die Anzeige im Backend verwendet, sofern diese an den entsprechenden Stellen nicht überschrieben werden.'
help: ''
