label: 'Team strukturiert'
description: 'The <em>Team structured</em> is a set of functionalities and data structures that allows you to capture topic contributions, which can be supplemented based on structured data.'

